<?php

use App\Helpers\SeoHelper;

// Khởi tạo SeoHelper nếu chưa được set từ controller
SeoHelper::init();
?>
<!DOCTYPE html>
<html lang="vi">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">

    <!-- Dynamic Title -->
    <title><?= SeoHelper::getTitle() ?></title>

    <!-- SEO Meta Tags (Generated by SeoHelper) -->
    <?= SeoHelper::render() ?>

    <!-- Favicon -->
    <?php if (!empty($siteSettings['general']['site_favicon'])): ?>
        <link rel="icon" href="<?= $siteSettings['general']['site_favicon'] ?>">
    <?php endif; ?>

    <link rel="icon" href="/images/icons/favicon.ico" />
    <link rel="icon" type="image/png" sizes="32x32" href="/images/icons/favicon-32x32.png" />
    <link rel="apple-touch-icon" sizes="180x180" href="/images/icons/apple-touch-icon.png" />
    <link rel="manifest" href="/images/site.webmanifest" />
    <meta name="theme-color" content="#2C67C8" />

    <!-- Stylesheets -->
    <link rel="stylesheet" href="/assets/css/app.css">
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

    <style>
        body {
            font-family: 'Quicksand', sans-serif;
        }

        /* Mobile UX Utilities */
        .scrollbar-none {
            -ms-overflow-style: none;
            scrollbar-width: none;
        }

        .scrollbar-none::-webkit-scrollbar {
            display: none;
        }

        .safe-area-top {
            padding-top: env(safe-area-inset-top);
        }

        .safe-area-bottom {
            padding-bottom: env(safe-area-inset-bottom);
        }
    </style>
</head>

<body class="bg-gray-50">